sudo: required

services:
  - docker

before_install:
  - docker build -t idkla/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true idkla/react-test npm test 

after_success:
  - docker build -t idkla/multi-client ./client
  - docker build -t idkla/multi-nginx ./nginx
  - docker build -t idkla/multi-server ./server
  - docker build -t idkla/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push idkla/multi-client
  - docker push idkla/multi-nginx
  - docker push idkla/multi-server
  - docker push idkla/multi-worker
  