sudo: required

services:
  - docker

before_install:
  - docker build -t wk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wk/react-test npm test 

after_success:
  - docker build -t wk/multi-client ./client
  - docker build -t wk/multi-nginx ./nginx
  - docker build -t wk/multi-server ./server
  - docker build -t wk/multi-worker ./worker

  # login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push wk/multi-client
  - docker push wk/multi-nginx
  - docker push wk/multi-server
  - docker push wk/multi-worker
  